#!/usr/bin/env python3
"""Check five HelloWorld-related signatures against the SDK GNU wrappers.

The limited type translation here is a verification aid, not a header generator.
"""
import hashlib
import json
from pathlib import Path
import re
from inspect_format import inspect

ROOT = Path(__file__).resolve().parents[2]
SDK = ROOT / 'software/mips/sdk/extracted/MagicDeveloper/MagicDeveloper/Interfaces'


def c_type(type_ref, flags=0, parameter=False):
    name = type_ref['name_latin1']
    if name == 'void' or name in ('Unsigned', 'Signed'):
        return name
    if type_ref['raw_kind'] == 1:
        return 'Reference'
    if name == 'Box' and parameter and flags in (0, 128):
        return ('const ' if flags == 0 else '') + 'Box *'
    raise ValueError(f'unverified type translation: {type_ref}, flags={flags}')


def main():
    paths = [SDK / 'MagicCap.cx', SDK / 'Apollo/MagicCap.gnu.xh']
    image = inspect(paths[0].read_bytes())
    header = paths[1].read_bytes().decode('mac_roman').replace('\r', '\n')
    operations = {r['name_latin1']: r for s in image['sections'] if s['raw_tag'] == 16
                  for r in s['named_records']}
    checks = []
    for name in ('Draw', 'FillBox', 'ContentBox', 'PartColor', 'CurrentCanvas'):
        sig = operations[name]['signature']
        result_type = c_type(sig['return_type'])
        parameters = [c_type(p['type'], p['raw_flags_byte'], True) for p in sig['parameters']]
        if name == 'CurrentCanvas':
            match = re.search(r'inline\s+(\w+)\s+CurrentCanvas\(\)', header)
            if not match:
                raise ValueError('missing CurrentCanvas wrapper')
            actual = {'return_type': result_type, 'parameters': parameters}
            expected = {'return_type': match.group(1), 'parameters': []}
        else:
            match = re.search(r'(\w+) __1d_' + name + r'\(([^)]*)\);', header)
            if not match:
                raise ValueError(f'missing {name} wrapper')
            # Dispatcher address, selector and implicit self are generated by
            # the SDK; they are not explicit parameters in the .cdef record.
            actual = {'return_type': result_type,
                      'parameters': ['DispatcherAddress', 'int', 'Reference', *parameters]}
            expected = {'return_type': match.group(1),
                        'parameters': [p.strip() for p in match.group(2).split(',')]}
        checks.append({'operation': name, 'decoded': actual, 'header': expected,
                       'match': actual == expected})
    report = {'scope': 'five selected signatures; type translation is intentionally limited',
              'sources': {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},
              'checks': checks}
    output = ROOT / 'out/rosemary-inspection/signature-comparison.json'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2) + '\n')
    failures = sum(not c['match'] for c in checks)
    print(f'{len(checks)} signature comparisons, {failures} mismatches')
    return int(bool(failures))


if __name__ == '__main__':
    raise SystemExit(main())
